Created roles guard
Lunessr/nest-js pull request #4
Opened 2022-06-14 09:53 UTC by Lunessr

2022-06-14 10:26 UTC, rudenkose requested changes
Looks good, but a few comments inside

2022-06-14 10:26 UTC, rudenkose commented on src/decorators/roles.decorator.ts
> +export const ROLES_KEY = "roles";
this have to be moved to constants

2022-06-14 10:26 UTC, rudenkose commented on src/guards/roles.guard.ts
> +    return requiredRoles.some((role) => user.role?.includes(role));
why do we need `user.role?` ? in the end?
do we have the case when user have no roles?

2022-06-14 10:26 UTC, rudenkose commented on src/users/customer.user.service.ts
> +    filter.role = "Customer";
You have to use `enum`

2022-06-14 10:26 UTC, rudenkose commented on src/users/users.repository.ts
> +    let skip;
why can't we use empty object as initial state for our _find request params?_

2022-06-15 12:11 UTC, rudenkose approved these changes
Looks good!
minor comments inside

2022-06-15 12:11 UTC, rudenkose commented on src/users/admin.users.service.ts
> +    let {
why do we need to change it to let?

2022-06-15 12:11 UTC, rudenkose commented on src/users/admin.users.service.ts
> +      { id: userWithEmail.id, role: userWithEmail.role },
hah, nice catch!

2022-06-15 12:11 UTC, rudenkose commented on src/users/customer.user.service.ts
> +    let {
why let again?

2022-06-16 07:42 UTC, Lunessr commented on src/users/admin.users.service.ts
> +    let {
we don't need this "let". I forgot to rewrite it to "const"

2022-06-16 07:57 UTC, merged